apiVersion: v1
kind: Service
metadata:
  name: python-calculator-service
spec:
  type: NodePort
  selector:
    app: python-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

