apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-calculator
  template:
    metadata:
      labels:
        app: python-calculator
    spec:
      containers:
      - name: python-calculator
        image: premrepal/python-calculator:16
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

